/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScreeningQueueRouteImport } from './routes/screening-queue'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as IntegrationRouteImport } from './routes/integration'
import { Route as IliReportRouteImport } from './routes/ili-report'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AgentBenchRouteImport } from './routes/agent-bench'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LineStaffRouteImport } from './routes/line.staff'
import { Route as LineScreeningRouteImport } from './routes/line.screening'
import { Route as LineLinkRouteImport } from './routes/line.link'
import { Route as ApiSubmitMophReportRouteImport } from './routes/api/submit-moph-report'
import { Route as ApiSendNudgeRouteImport } from './routes/api/send-nudge'
import { Route as ApiScreeningBookingsRouteImport } from './routes/api/screening-bookings'
import { Route as ApiProductionAutomationRouteImport } from './routes/api/production-automation'
import { Route as ApiOpsMonitoringRouteImport } from './routes/api/ops-monitoring'
import { Route as ApiLineWebhookRouteImport } from './routes/api/line-webhook'
import { Route as ApiKumhosProxyRouteImport } from './routes/api/kumhos-proxy'
import { Route as ApiIliReportRouteImport } from './routes/api/ili-report'
import { Route as ApiHosxpSyncRouteImport } from './routes/api/hosxp-sync'
import { Route as ApiHosxpBridgeRouteImport } from './routes/api/hosxp-bridge'
import { Route as ApiConnectionStatusRouteImport } from './routes/api/connection-status'
import { Route as ApiCareGapQueueRouteImport } from './routes/api/care-gap-queue'
import { Route as ApiAgentWorldBenchRouteImport } from './routes/api/agent-world-bench'
import { Route as ApiAgentOrchestratorRouteImport } from './routes/api/agent-orchestrator'

const ScreeningQueueRoute = ScreeningQueueRouteImport.update({
  id: '/screening-queue',
  path: '/screening-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationRoute = IntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => rootRouteImport,
} as any)
const IliReportRoute = IliReportRouteImport.update({
  id: '/ili-report',
  path: '/ili-report',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentBenchRoute = AgentBenchRouteImport.update({
  id: '/agent-bench',
  path: '/agent-bench',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LineStaffRoute = LineStaffRouteImport.update({
  id: '/line/staff',
  path: '/line/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const LineScreeningRoute = LineScreeningRouteImport.update({
  id: '/line/screening',
  path: '/line/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const LineLinkRoute = LineLinkRouteImport.update({
  id: '/line/link',
  path: '/line/link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitMophReportRoute = ApiSubmitMophReportRouteImport.update({
  id: '/api/submit-moph-report',
  path: '/api/submit-moph-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendNudgeRoute = ApiSendNudgeRouteImport.update({
  id: '/api/send-nudge',
  path: '/api/send-nudge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScreeningBookingsRoute = ApiScreeningBookingsRouteImport.update({
  id: '/api/screening-bookings',
  path: '/api/screening-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductionAutomationRoute = ApiProductionAutomationRouteImport.update({
  id: '/api/production-automation',
  path: '/api/production-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsMonitoringRoute = ApiOpsMonitoringRouteImport.update({
  id: '/api/ops-monitoring',
  path: '/api/ops-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLineWebhookRoute = ApiLineWebhookRouteImport.update({
  id: '/api/line-webhook',
  path: '/api/line-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKumhosProxyRoute = ApiKumhosProxyRouteImport.update({
  id: '/api/kumhos-proxy',
  path: '/api/kumhos-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIliReportRoute = ApiIliReportRouteImport.update({
  id: '/api/ili-report',
  path: '/api/ili-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHosxpSyncRoute = ApiHosxpSyncRouteImport.update({
  id: '/api/hosxp-sync',
  path: '/api/hosxp-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHosxpBridgeRoute = ApiHosxpBridgeRouteImport.update({
  id: '/api/hosxp-bridge',
  path: '/api/hosxp-bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectionStatusRoute = ApiConnectionStatusRouteImport.update({
  id: '/api/connection-status',
  path: '/api/connection-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCareGapQueueRoute = ApiCareGapQueueRouteImport.update({
  id: '/api/care-gap-queue',
  path: '/api/care-gap-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentWorldBenchRoute = ApiAgentWorldBenchRouteImport.update({
  id: '/api/agent-world-bench',
  path: '/api/agent-world-bench',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentOrchestratorRoute = ApiAgentOrchestratorRouteImport.update({
  id: '/api/agent-orchestrator',
  path: '/api/agent-orchestrator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/agent-bench': typeof AgentBenchRoute
  '/architecture': typeof ArchitectureRoute
  '/health': typeof HealthRoute
  '/ili-report': typeof IliReportRoute
  '/integration': typeof IntegrationRoute
  '/patients': typeof PatientsRoute
  '/screening-queue': typeof ScreeningQueueRoute
  '/api/agent-orchestrator': typeof ApiAgentOrchestratorRoute
  '/api/agent-world-bench': typeof ApiAgentWorldBenchRoute
  '/api/care-gap-queue': typeof ApiCareGapQueueRoute
  '/api/connection-status': typeof ApiConnectionStatusRoute
  '/api/hosxp-bridge': typeof ApiHosxpBridgeRoute
  '/api/hosxp-sync': typeof ApiHosxpSyncRoute
  '/api/ili-report': typeof ApiIliReportRoute
  '/api/kumhos-proxy': typeof ApiKumhosProxyRoute
  '/api/line-webhook': typeof ApiLineWebhookRoute
  '/api/ops-monitoring': typeof ApiOpsMonitoringRoute
  '/api/production-automation': typeof ApiProductionAutomationRoute
  '/api/screening-bookings': typeof ApiScreeningBookingsRoute
  '/api/send-nudge': typeof ApiSendNudgeRoute
  '/api/submit-moph-report': typeof ApiSubmitMophReportRoute
  '/line/link': typeof LineLinkRoute
  '/line/screening': typeof LineScreeningRoute
  '/line/staff': typeof LineStaffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/agent-bench': typeof AgentBenchRoute
  '/architecture': typeof ArchitectureRoute
  '/health': typeof HealthRoute
  '/ili-report': typeof IliReportRoute
  '/integration': typeof IntegrationRoute
  '/patients': typeof PatientsRoute
  '/screening-queue': typeof ScreeningQueueRoute
  '/api/agent-orchestrator': typeof ApiAgentOrchestratorRoute
  '/api/agent-world-bench': typeof ApiAgentWorldBenchRoute
  '/api/care-gap-queue': typeof ApiCareGapQueueRoute
  '/api/connection-status': typeof ApiConnectionStatusRoute
  '/api/hosxp-bridge': typeof ApiHosxpBridgeRoute
  '/api/hosxp-sync': typeof ApiHosxpSyncRoute
  '/api/ili-report': typeof ApiIliReportRoute
  '/api/kumhos-proxy': typeof ApiKumhosProxyRoute
  '/api/line-webhook': typeof ApiLineWebhookRoute
  '/api/ops-monitoring': typeof ApiOpsMonitoringRoute
  '/api/production-automation': typeof ApiProductionAutomationRoute
  '/api/screening-bookings': typeof ApiScreeningBookingsRoute
  '/api/send-nudge': typeof ApiSendNudgeRoute
  '/api/submit-moph-report': typeof ApiSubmitMophReportRoute
  '/line/link': typeof LineLinkRoute
  '/line/screening': typeof LineScreeningRoute
  '/line/staff': typeof LineStaffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/agent-bench': typeof AgentBenchRoute
  '/architecture': typeof ArchitectureRoute
  '/health': typeof HealthRoute
  '/ili-report': typeof IliReportRoute
  '/integration': typeof IntegrationRoute
  '/patients': typeof PatientsRoute
  '/screening-queue': typeof ScreeningQueueRoute
  '/api/agent-orchestrator': typeof ApiAgentOrchestratorRoute
  '/api/agent-world-bench': typeof ApiAgentWorldBenchRoute
  '/api/care-gap-queue': typeof ApiCareGapQueueRoute
  '/api/connection-status': typeof ApiConnectionStatusRoute
  '/api/hosxp-bridge': typeof ApiHosxpBridgeRoute
  '/api/hosxp-sync': typeof ApiHosxpSyncRoute
  '/api/ili-report': typeof ApiIliReportRoute
  '/api/kumhos-proxy': typeof ApiKumhosProxyRoute
  '/api/line-webhook': typeof ApiLineWebhookRoute
  '/api/ops-monitoring': typeof ApiOpsMonitoringRoute
  '/api/production-automation': typeof ApiProductionAutomationRoute
  '/api/screening-bookings': typeof ApiScreeningBookingsRoute
  '/api/send-nudge': typeof ApiSendNudgeRoute
  '/api/submit-moph-report': typeof ApiSubmitMophReportRoute
  '/line/link': typeof LineLinkRoute
  '/line/screening': typeof LineScreeningRoute
  '/line/staff': typeof LineStaffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/agent-bench'
    | '/architecture'
    | '/health'
    | '/ili-report'
    | '/integration'
    | '/patients'
    | '/screening-queue'
    | '/api/agent-orchestrator'
    | '/api/agent-world-bench'
    | '/api/care-gap-queue'
    | '/api/connection-status'
    | '/api/hosxp-bridge'
    | '/api/hosxp-sync'
    | '/api/ili-report'
    | '/api/kumhos-proxy'
    | '/api/line-webhook'
    | '/api/ops-monitoring'
    | '/api/production-automation'
    | '/api/screening-bookings'
    | '/api/send-nudge'
    | '/api/submit-moph-report'
    | '/line/link'
    | '/line/screening'
    | '/line/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/agent-bench'
    | '/architecture'
    | '/health'
    | '/ili-report'
    | '/integration'
    | '/patients'
    | '/screening-queue'
    | '/api/agent-orchestrator'
    | '/api/agent-world-bench'
    | '/api/care-gap-queue'
    | '/api/connection-status'
    | '/api/hosxp-bridge'
    | '/api/hosxp-sync'
    | '/api/ili-report'
    | '/api/kumhos-proxy'
    | '/api/line-webhook'
    | '/api/ops-monitoring'
    | '/api/production-automation'
    | '/api/screening-bookings'
    | '/api/send-nudge'
    | '/api/submit-moph-report'
    | '/line/link'
    | '/line/screening'
    | '/line/staff'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/agent-bench'
    | '/architecture'
    | '/health'
    | '/ili-report'
    | '/integration'
    | '/patients'
    | '/screening-queue'
    | '/api/agent-orchestrator'
    | '/api/agent-world-bench'
    | '/api/care-gap-queue'
    | '/api/connection-status'
    | '/api/hosxp-bridge'
    | '/api/hosxp-sync'
    | '/api/ili-report'
    | '/api/kumhos-proxy'
    | '/api/line-webhook'
    | '/api/ops-monitoring'
    | '/api/production-automation'
    | '/api/screening-bookings'
    | '/api/send-nudge'
    | '/api/submit-moph-report'
    | '/line/link'
    | '/line/screening'
    | '/line/staff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  AgentBenchRoute: typeof AgentBenchRoute
  ArchitectureRoute: typeof ArchitectureRoute
  HealthRoute: typeof HealthRoute
  IliReportRoute: typeof IliReportRoute
  IntegrationRoute: typeof IntegrationRoute
  PatientsRoute: typeof PatientsRoute
  ScreeningQueueRoute: typeof ScreeningQueueRoute
  ApiAgentOrchestratorRoute: typeof ApiAgentOrchestratorRoute
  ApiAgentWorldBenchRoute: typeof ApiAgentWorldBenchRoute
  ApiCareGapQueueRoute: typeof ApiCareGapQueueRoute
  ApiConnectionStatusRoute: typeof ApiConnectionStatusRoute
  ApiHosxpBridgeRoute: typeof ApiHosxpBridgeRoute
  ApiHosxpSyncRoute: typeof ApiHosxpSyncRoute
  ApiIliReportRoute: typeof ApiIliReportRoute
  ApiKumhosProxyRoute: typeof ApiKumhosProxyRoute
  ApiLineWebhookRoute: typeof ApiLineWebhookRoute
  ApiOpsMonitoringRoute: typeof ApiOpsMonitoringRoute
  ApiProductionAutomationRoute: typeof ApiProductionAutomationRoute
  ApiScreeningBookingsRoute: typeof ApiScreeningBookingsRoute
  ApiSendNudgeRoute: typeof ApiSendNudgeRoute
  ApiSubmitMophReportRoute: typeof ApiSubmitMophReportRoute
  LineLinkRoute: typeof LineLinkRoute
  LineScreeningRoute: typeof LineScreeningRoute
  LineStaffRoute: typeof LineStaffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/screening-queue': {
      id: '/screening-queue'
      path: '/screening-queue'
      fullPath: '/screening-queue'
      preLoaderRoute: typeof ScreeningQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration': {
      id: '/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof IntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ili-report': {
      id: '/ili-report'
      path: '/ili-report'
      fullPath: '/ili-report'
      preLoaderRoute: typeof IliReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-bench': {
      id: '/agent-bench'
      path: '/agent-bench'
      fullPath: '/agent-bench'
      preLoaderRoute: typeof AgentBenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line/staff': {
      id: '/line/staff'
      path: '/line/staff'
      fullPath: '/line/staff'
      preLoaderRoute: typeof LineStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line/screening': {
      id: '/line/screening'
      path: '/line/screening'
      fullPath: '/line/screening'
      preLoaderRoute: typeof LineScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line/link': {
      id: '/line/link'
      path: '/line/link'
      fullPath: '/line/link'
      preLoaderRoute: typeof LineLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-moph-report': {
      id: '/api/submit-moph-report'
      path: '/api/submit-moph-report'
      fullPath: '/api/submit-moph-report'
      preLoaderRoute: typeof ApiSubmitMophReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-nudge': {
      id: '/api/send-nudge'
      path: '/api/send-nudge'
      fullPath: '/api/send-nudge'
      preLoaderRoute: typeof ApiSendNudgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/screening-bookings': {
      id: '/api/screening-bookings'
      path: '/api/screening-bookings'
      fullPath: '/api/screening-bookings'
      preLoaderRoute: typeof ApiScreeningBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/production-automation': {
      id: '/api/production-automation'
      path: '/api/production-automation'
      fullPath: '/api/production-automation'
      preLoaderRoute: typeof ApiProductionAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops-monitoring': {
      id: '/api/ops-monitoring'
      path: '/api/ops-monitoring'
      fullPath: '/api/ops-monitoring'
      preLoaderRoute: typeof ApiOpsMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/line-webhook': {
      id: '/api/line-webhook'
      path: '/api/line-webhook'
      fullPath: '/api/line-webhook'
      preLoaderRoute: typeof ApiLineWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kumhos-proxy': {
      id: '/api/kumhos-proxy'
      path: '/api/kumhos-proxy'
      fullPath: '/api/kumhos-proxy'
      preLoaderRoute: typeof ApiKumhosProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ili-report': {
      id: '/api/ili-report'
      path: '/api/ili-report'
      fullPath: '/api/ili-report'
      preLoaderRoute: typeof ApiIliReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hosxp-sync': {
      id: '/api/hosxp-sync'
      path: '/api/hosxp-sync'
      fullPath: '/api/hosxp-sync'
      preLoaderRoute: typeof ApiHosxpSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hosxp-bridge': {
      id: '/api/hosxp-bridge'
      path: '/api/hosxp-bridge'
      fullPath: '/api/hosxp-bridge'
      preLoaderRoute: typeof ApiHosxpBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connection-status': {
      id: '/api/connection-status'
      path: '/api/connection-status'
      fullPath: '/api/connection-status'
      preLoaderRoute: typeof ApiConnectionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/care-gap-queue': {
      id: '/api/care-gap-queue'
      path: '/api/care-gap-queue'
      fullPath: '/api/care-gap-queue'
      preLoaderRoute: typeof ApiCareGapQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-world-bench': {
      id: '/api/agent-world-bench'
      path: '/api/agent-world-bench'
      fullPath: '/api/agent-world-bench'
      preLoaderRoute: typeof ApiAgentWorldBenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-orchestrator': {
      id: '/api/agent-orchestrator'
      path: '/api/agent-orchestrator'
      fullPath: '/api/agent-orchestrator'
      preLoaderRoute: typeof ApiAgentOrchestratorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  AgentBenchRoute: AgentBenchRoute,
  ArchitectureRoute: ArchitectureRoute,
  HealthRoute: HealthRoute,
  IliReportRoute: IliReportRoute,
  IntegrationRoute: IntegrationRoute,
  PatientsRoute: PatientsRoute,
  ScreeningQueueRoute: ScreeningQueueRoute,
  ApiAgentOrchestratorRoute: ApiAgentOrchestratorRoute,
  ApiAgentWorldBenchRoute: ApiAgentWorldBenchRoute,
  ApiCareGapQueueRoute: ApiCareGapQueueRoute,
  ApiConnectionStatusRoute: ApiConnectionStatusRoute,
  ApiHosxpBridgeRoute: ApiHosxpBridgeRoute,
  ApiHosxpSyncRoute: ApiHosxpSyncRoute,
  ApiIliReportRoute: ApiIliReportRoute,
  ApiKumhosProxyRoute: ApiKumhosProxyRoute,
  ApiLineWebhookRoute: ApiLineWebhookRoute,
  ApiOpsMonitoringRoute: ApiOpsMonitoringRoute,
  ApiProductionAutomationRoute: ApiProductionAutomationRoute,
  ApiScreeningBookingsRoute: ApiScreeningBookingsRoute,
  ApiSendNudgeRoute: ApiSendNudgeRoute,
  ApiSubmitMophReportRoute: ApiSubmitMophReportRoute,
  LineLinkRoute: LineLinkRoute,
  LineScreeningRoute: LineScreeningRoute,
  LineStaffRoute: LineStaffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
